language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    fast_finish: true

services:
    - mysql
    - postgresql

install:
    - composer selfupdate
    - composer install

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        recipients:
            - poisoncorpsee@gmail.com

        on_success: always
        on_failure: always
